# Pig Latin Basics

Pig Latin is the language used to analyze data in Hadoop using Apache Pig. In this chapter, we are going to discuss the basics of Pig Latin such as Pig Latin statements, data types, general and relational operators, and Pig Latin UDF’s.

Pig Latin – Data Model
---
As discussed in the previous chapters, the data model of Pig is fully nested. A Relation is the outermost structure of the Pig Latin data model. And it is a bag where −

- A bag is a collection of tuples.
- A tuple is an ordered set of fields.
- A field is a piece of data.

Pig Latin – Statemets
---
While processing data using Pig Latin, statements are the basic constructs.

- These statements work with relations. They include expressions and schemas.

- Every statement ends with a semicolon (;).

- We will perform various operations using operators provided by Pig Latin, through statements.

- Except LOAD and STORE, while performing all other operations, Pig Latin statements take a relation as input and produce another relation as output.

- As soon as you enter a Load statement in the Grunt shell, its semantic checking will be carried out. To see the contents of the schema, you need to use the Dump operator. Only after performing the dump operation, the MapReduce job for loading the data into the file system will be carried out.

<b>Example</b>
Given below is a Pig Latin statement, which loads data to Apache Pig.

grunt> Student_data = LOAD 'student_data.txt' USING PigStorage(',')as 
   ( id:int, firstname:chararray, lastname:chararray, phone:chararray, city:chararray );

Pig Latin – Data types
---
Given below table describes the Pig Latin data types.

<table class="table table-bordered">
<tr>
<th>S.N.</th>
<th style="text-align:center;width:20%;">Data Type</th>
<th>Description &amp; Example</th>
</tr>
<tr>
<td>1</td>
<td>int</td>
<td><p>Represents a signed 32-bit integer.</p>
<p><b>Example</b> : 8</p>
</td>
</tr>
<tr>
<td>2</td>
<td>long</td>
<td><p>Represents a signed 64-bit integer.</p> 
<p><b>Example</b> : 5L</p>
</td>
</tr>
<tr>
<td>3</td>
<td>float</td>
<td><p>Represents a signed 32-bit floating point.</p>
<p><b>Example</b> : 5.5F</p>
</td>
</tr>
<tr>
<td>4</td>
<td>double</td>
<td><p>Represents a 64-bit floating point.</p>
<p><b>Example</b> : 10.5</p>
</td>
</tr>
<tr>
<td>5</td>
<td>chararray</td>
<td><p>Represents a character array (string) in Unicode UTF-8 format.</p>
<p><b>Example</b> : ‘tutorials point’</p>
</td>
</tr>
<tr>
<td>6</td>
<td>Bytearray</td>
<td><p>Represents a Byte array (blob).</p>
</td>
</tr>
<tr>
<td>7</td>
<td>Boolean</td>
<td><p>Represents a Boolean value.</p>
<p><b>Example</b> : true/ false.</p>
</td>
</tr>
<tr>
<td>8</td>
<td>Datetime</td>
<td><p>Represents a date-time.</p>
<p><b>Example</b> : 1970-01-01T00:00:00.000+00:00</p>
</td>
</tr>
<tr>
<td>9</td>
<td>Biginteger</td>
<td><p>Represents a Java BigInteger.</p>
<p><b>Example</b> : 60708090709</p>
</td>
</tr>
<tr>
<td>10</td>
<td>Bigdecimal</td>
<td><p>Represents a  Java BigDecimal</p>
<p><b>Example</b> : 185.98376256272893883</p>
</td>
</tr>
<tr>
<th style="text-align:center;" colspan="3">Complex Types</th>
</tr>
<tr>
<td>11</td>
<td>Tuple</td>
<td><p>A tuple is an ordered set of fields.</p>
<p><b>Example</b> : (raja, 30)</p>
</td>
</tr>
<tr>
<td>12</td>
<td>Bag</td>
<td><p>A bag is a collection of tuples.</p>
<p><b>Example</b> : {(raju,30),(Mohhammad,45)}</p></td>
</tr>
<tr>
<td>13</td>
<td>Map</td>
<td><p>A Map is a set of key-value pairs.</p>
<p><b>Example</b> : [ ‘name’#’Raju’, ‘age’#30]</p></td>
</tr>
</table>

Null Values
---
Values for all the above data types can be NULL. Apache Pig treats null values in a similar way as SQL does.

A null can be an unknown value or a non-existent value. It is used as a placeholder for optional values. These nulls can occur naturally or can be the result of an operation.

Pig Latin – Arithmetic Operators
---
The following table describes the arithmetic operators of Pig Latin. Suppose a = 10 and b = 20.

<table class="table table-bordered">
<tr>
<th>Operator</th>
<th>Description</th>
<th>Example</th>
</tr>
<tr>
<td style="text-align:center;">&plus;</td>
<td><p><b>Addition</b> &minus; Adds values on either side of the operator</p></td>
<td>a &plus; b will give 30</td>
</tr>
<tr>
<td style="text-align:center;">&minus;</td>
<td><p><b>Subtraction</b> &minus; Subtracts right hand operand from left hand operand</p></td>
<td>a &minus; b will give &minus;10</td>
</tr>
<tr>
<td style="text-align:center;">*</td>
<td><p><b>Multiplication</b> &minus; Multiplies values on either side of the operator</p></td>
<td>a * b will give 200</td>
</tr>
<tr>
<td style="text-align:center;">/</td>
<td><p><b>Division</b> &minus; Divides left hand operand by right hand operand</p></td>
<td>b / a will give 2</td>
</tr>
<tr>
<td style="text-align:center;">%</td>
<td><p><b>Modulus</b> &minus; Divides left hand operand by right hand operand and returns remainder</p></td>
<td>b % a will give 0</td>
</tr>
<tr>
<td style="text-align:center;vertical-align:middle;">? :</td>
<td><p><b>Bincond</b> &minus; Evaluates the Boolean operators. It has three operands as shown below.</p>
<p>variable <b>x</b> = (expression) ? <b>value1</b> <i>if true</i> : <b>value2</b> <i>if false</i>.</p></td>
<td><p>b = (a == 1)? 20: 30;</p>
<p>if a = 1 the value of b is 20.</p>
<p>if a!=1 the value of b is 30.</p></td>
</tr>
<tr>
<td style="text-align:center;"><p>CASE</p><p>WHEN</p><p>THEN</p><p>ELSE END</p></td>
<td><p><b>Case</b> &minus; The case operator is equivalent to nested bincond operator.</p></td>
<td><p>CASE f2 % 2</p>
<p style="padding-left:16%;">WHEN 0 THEN 'even'</p>
<p style="padding-left:16%;">WHEN 1 THEN 'odd'</p>
<p>END</p></td>
</tr>
</table>
<h2>Pig Latin – Comparison Operators</h2>
<p>The following table describes the comparison operators of Pig Latin.</p>
<table class="table table-bordered">
<tr>
<th>Operator</th>
<th>Description</th>
<th>Example</th>
</tr>
<tr>
<td style="text-align:center;">==</td>
<td><p><b>Equal</b> &minus; Checks if the values of two operands are equal or not; if yes, then the condition becomes true.</p></td>
<td>(a = b) is not true</td>
</tr>
<tr>
<td style="text-align:center;">!=</td>
<td><p><b>Not Equal</b> &minus; Checks if the values of two operands are equal or not. If the values are not equal, then condition becomes true.</p></td>
<td>(a != b) is true.</td>
</tr>
<tr>
<td style="text-align:center;">&gt;</td>
<td><p><b>Greater than</b> &minus; Checks if the value of the left operand is greater than the value of the right operand. If yes, then the condition becomes true.</p></td>
<td>(a &gt; b) is not true.</td>
</tr>
<tr>
<td style="text-align:center;">&lt;</td>
<td><p><b>Less than</b> &minus; Checks if the value of the left operand is less than the value of the right operand. If yes, then the condition becomes true.</p></td>
<td>(a &lt; b) is true.</td>
</tr>
<tr>
<td style="text-align:center;">&gt;=</td>
<td><p><b>Greater than or equal to</b> &minus; Checks if the value of the left operand is greater than or equal to the value of the right operand. If yes, then the condition becomes true.</p></td>
<td>(a &gt;= b) is not true.</td>
</tr>
<tr>
<td style="text-align:center;">&lt;=</td>
<td><p><b>Less than or equal to</b> &minus; Checks if the value of the left operand is less than or equal to the value of the right operand. If yes, then the condition becomes true.</p></td>
<td>(a &lt;= b) is true.</td>
</tr>
<tr>
<td style="text-align:center;">matches</td>
<td><p><b>Pattern matching</b> &minus; Checks whether the string in the left-hand side matches with the constant in the right-hand side.</p></td>
<td>f1 matches '.*tutorial.*'</td>
</tr>
</table>
<h2>Pig Latin – Type Construction Operators</h2>
<p>The following table describes the Type construction operators of Pig Latin.</p>
<table class="table table-bordered">
<tr>
<th>Operator</th>
<th>Description</th>
<th>Example</th>
</tr>
<tr>
<td style="text-align:center;">()</td>
<td><p><b>Tuple constructor operator</b> &minus; This operator is used to construct a tuple.</p></td>
<td>(Raju, 30)</td>
</tr>
<tr>
<td style="text-align:center;">{}</td>
<td><p><b>Bag constructor operator</b> &minus; This operator is used to construct a bag.</p></td>
<td>{(Raju, 30), (Mohammad, 45)}</td>
</tr>
<tr>
<td style="text-align:center;">[]</td>
<td><p><b>Map constructor operator</b> &minus; This operator is used to construct a tuple.</p></td>
<td>[name#Raja, age#30]</td>
</tr>
</table>
<h2>Pig Latin – Relational Operations</h2>
<p>The following table describes the relational operators of Pig Latin.</p>
<table class="table table-bordered">
<tr>
<th>Operator</th>
<th style="text-align:center;">Description</th>
</tr>
<tr>
<td style="text-align:center;" colspan="2"><b>Loading and Storing</b></td>
</tr>
<tr>
<td>LOAD</td>
<td>To Load the data from the file system (local/HDFS) into a relation.</td>
</tr>
<tr>
<td>STORE</td>
<td>To save a relation to the file system (local/HDFS).</td>
</tr>
<tr>
<th style="text-align:center;" colspan="2">Filtering</th>
</tr>
<tr>
<td>FILTER</td>
<td>To remove unwanted rows from a relation.</td>
</tr>
<tr>
<td>DISTINCT</td>
<td>To remove duplicate rows from a relation.</td>
</tr>
<tr>
<td style="width:30%;">FOREACH, GENERATE</td>
<td>To generate data transformations based on columns of data.</td>
</tr>
<tr>
<td>STREAM</td>
<td>To transform a relation using an external program.</td>
</tr>
<tr>
<th style="text-align:center;" colspan="2">Grouping and Joining</th>
</tr>
<tr>
<td>JOIN</td>
<td>To join two or more relations.</td>
</tr>
<tr>
<td>COGROUP</td>
<td>To group the data in two or more relations.</td>
</tr>
<tr>
<td>GROUP</td>
<td>To group the data in a single relation.</td>
</tr>
<tr>
<td>CROSS</td>
<td>To create the cross product of two or more relations.</td>
</tr>
<tr>
<th style="text-align:center;" colspan="2">Sorting</th>
</tr>
<tr>
<td>ORDER</td>
<td>To arrange a relation in a sorted order based on one or more fields (ascending or descending).</td>
</tr>
<tr>
<td>LIMIT</td>
<td>To get a limited number of tuples from a relation.</td>
</tr>
<tr>
<th style="text-align:center;" colspan="2">Combining and Splitting</th>
</tr>
<tr>
<td>UNION</td>
<td>To combine two or more relations into a single relation.</td>
</tr>
<tr>
<td>SPLIT</td>
<td>To split a single relation into two or more relations.</td>
</tr>
<tr>
<th style="text-align:center;" colspan="2">Diagnostic Operators</th>
</tr>
<tr>
<td>DUMP</td>
<td>To print the contents of a relation on the console.</td>
</tr>
<tr>
<td>DESCRIBE</td>
<td>To describe the schema of a relation.</td>
</tr>
<tr>
<td>EXPLAIN</td>
<td>To view the logical, physical, or MapReduce execution plans to compute a relation.</td>
</tr>
<tr>
<td>ILLUSTRATE</td>
<td>To view the step-by-step execution of a series of statements.</td>
</tr>
</table>